// generated by compute-ber.py
// table for rate 3 (exact)
// (computed without odd hints)

double get_ber_r3(UINT8 hint) {
   switch (hint) {
      case  0: return 0.500000000000000;
      case  1: return 0.284726004009016;
      case  2: return 0.128212895873559;
      case  3: return 0.067159891710926;
      case  4: return 0.021722546662050;
      case  5: return 0.012949708136332;
      case  6: return 0.003519890826004;
      case  7: return 0.002563013480070;
      case  8: return 0.000586504303693;
      case  9: return 0.000536911708464;
      case 10: return 0.000066685432285;
      case 11: return 0.000108321347493;
      case 12: return 0.000010775503933;
      case 13: return 0.000022862141858;
      case 14: return 0.000001141901860;
      case 15: return 0.000006081627092;
      case 16: return 0.000000095127091;
      case 17: return 0.000001184327664;
      case 18: return 0.000000003449106;
      case 19: return 0.000000400455398;
      case 20: return 0.000000000000000;
      case 21: return 0.000000000000000;
      case 22: return 0.000000000000000;
      case 23: return 0.000000000000000;
      case 24: return 0.000000000000000;
      case 25: return 0.000000000000000;
      case 26: return 0.000000000000000;
      case 27: return 0.000000000000000;
      case 28: return 0.000000000000000;
      case 29: return 0.000000000000000;
      case 30: return 0.000000000000000;
      case 31: return 0.000000000000000;
      case 32: return 0.000000000000000;
      case 33: return 0.000000000000000;
      case 34: return 0.000000000000000;
      case 35: return 0.000000000000000;
      case 36: return 0.000000000000000;
      case 37: return 0.000000000000000;
      case 38: return 0.000000000000000;
      case 39: return 0.000000000000000;
      case 40: return 0.000000000000000;
      case 41: return 0.000000000000000;
      case 42: return 0.000000000000000;
      case 43: return 0.000000000000000;
      case 44: return 0.000000000000000;
      case 45: return 0.000000000000000;
      case 46: return 0.000000000000000;
      case 47: return 0.000000000000000;
      case 48: return 0.000000000000000;
      case 49: return 0.000000000000000;
      case 50: return 0.000000000000000;
      case 51: return 0.000000000000000;
      case 52: return 0.000000000000000;
      case 53: return 0.000000000000000;
      case 54: return 0.000000000000000;
      case 55: return 0.000000000000000;
      case 56: return 0.000000000000000;
      case 57: return 0.000000000000000;
      case 58: return 0.000000000000000;
      case 59: return 0.000000000000000;
      case 60: return 0.000000000000000;
      case 61: return 0.000000000000000;
      case 62: return 0.000000000000000;
      case 63: return 0.000000000000000;
      default: return 0;
   }
}
