// generated by compute-ber.py
// table for rate 5 (exact)
// (computed without odd hints)

double get_ber_r5(UINT8 hint) {
   switch (hint) {
      case  0: return 0.500000000000000;
      case  1: return 0.390127346222532;
      case  2: return 0.280698246420164;
      case  3: return 0.207573956596331;
      case  4: return 0.128534722586869;
      case  5: return 0.095302809367405;
      case  6: return 0.051150850678179;
      case  7: return 0.040803939121653;
      case  8: return 0.018175148050883;
      case  9: return 0.016938647326589;
      case 10: return 0.006030518392690;
      case 11: return 0.006735769480732;
      case 12: return 0.001890001162689;
      case 13: return 0.002679567618821;
      case 14: return 0.000575495664579;
      case 15: return 0.001104210767227;
      case 16: return 0.000171991758240;
      case 17: return 0.000464345795423;
      case 18: return 0.000049746157487;
      case 19: return 0.000206430472658;
      case 20: return 0.000015362522297;
      case 21: return 0.000058266557344;
      case 22: return 0.000004585678520;
      case 23: return 0.000036614091543;
      case 24: return 0.000001447229630;
      case 25: return 0.000003737940470;
      case 26: return 0.000000292149423;
      case 27: return 0.000000000000000;
      case 28: return 0.000000078858435;
      case 29: return 0.000000000000000;
      case 30: return 0.000000000000000;
      case 31: return 0.000000000000000;
      case 32: return 0.000000000000000;
      case 33: return 0.000000000000000;
      case 34: return 0.000000000000000;
      case 35: return 0.000000000000000;
      case 36: return 0.000000000000000;
      case 37: return 0.000000000000000;
      case 38: return 0.000000000000000;
      case 39: return 0.000000000000000;
      case 40: return 0.000000000000000;
      case 41: return 0.000000000000000;
      case 42: return 0.000000000000000;
      case 43: return 0.000000000000000;
      case 44: return 0.000000000000000;
      case 45: return 0.000000000000000;
      case 46: return 0.000000000000000;
      case 47: return 0.000000000000000;
      case 48: return 0.000000000000000;
      case 49: return 0.000000000000000;
      case 50: return 0.000000000000000;
      case 51: return 0.000000000000000;
      case 52: return 0.000000000000000;
      case 53: return 0.000000000000000;
      case 54: return 0.000000000000000;
      case 55: return 0.000000000000000;
      case 56: return 0.000000000000000;
      case 57: return 0.000000000000000;
      case 58: return 0.000000000000000;
      case 59: return 0.000000000000000;
      case 60: return 0.000000000000000;
      case 61: return 0.000000000000000;
      case 62: return 0.000000000000000;
      case 63: return 0.000000000000000;
      default: return 0;
   }
}
